# Generated by Django 4.1 on 2024-01-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongSites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MahjongData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('matchnumber', models.IntegerField()),
                ('score', models.IntegerField()),
                ('rolenumber', models.IntegerField()),
                ('rolescore', models.IntegerField()),
                ('sumrank', models.IntegerField()),
                ('maxcount', models.IntegerField()),
                ('sumenemyrole', models.IntegerField()),
                ('summiss', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
